### ISSUE TITLE
Issue with gateway serial

### ISSUE THREAD

**Issue by rcastberg** [kolaf/homelypy#2]
Hi,

I am having issues using this library as it 

`$ python3 -m homelypy.homely  "user@name.com"
Password: 
Traceback (most recent call last):
  File "/home/rcastberg/.miniconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/rcastberg/.miniconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/rcastberg/.miniconda3/lib/python3.9/site-packages/homelypy/homely.py", line 244, in <module>
    locations = homely.get_locations()
  File "/home/rcastberg/.miniconda3/lib/python3.9/site-packages/homelypy/homely.py", line 151, in get_locations
    return [
  File "/home/rcastberg/.miniconda3/lib/python3.9/site-packages/homelypy/homely.py", line 157, in <listcomp>
    location_data["gatewayserial"],
KeyError: 'gatewayserial'
`

I dumped the response.json, which looks something like this: (I have sensored my values with randomness)
`[{'name': 'Veien', 'role': 'ADMIN', 'userId': '66061b9a-7f4e-a3d3-6754-43205b3421ad', 'locationId': 'b5f74727-13d2-4da9-ad51-fbaac2b15410'}]
`

Managed to have the code work well wihtout the gateway serial by replacing it with a string of numbers.

**Comment by perolavsvendsen** [comment]
According to Homely, the endpoint `homely/locations` will give `name`, `role`, `userId`, `LocationId`. The endpoint `homely/home/{locationId}` will return gateway serial + lots of other stuff.

The code, as-is, I believe assumes that gateway serial will be issued by the `homely/locations` endpoint.

I defaulted it to `None` in #4 and that also seems to work OK...
